### ISSUE TITLE
Bringing the package up to speed with newer versions of Haskell

### ISSUE THREAD

**Issue by andrejbauer** [andersk/haskell-constructible#1]
Is there any chance we could have an upgrade of this 6 year old package so that it works with the latest version of Haskell and Hackage?

**Comment by andersk** [comment]
I wasn’t aware there was anything broken. It works fine for me with GHC 8.6.5 and GHC 8.8.1 (with a handful of harmless build warnings). What specifically isn’t working for you?

**Comment by andrejbauer** [comment]
Hmmm, I'll try again and let you know. It might be a problem with my Haskell setup (although I use an updated version of Haskell from Homebrew).

**Comment by andersk** [comment]
“Doesn’t work” is never an actionable report, but if you can provide any information about what went wrong, including the commands you ran and any error messages you got, I’m happy to see if I can help.

**Comment by andrejbauer** [comment]
Will do when I get a minute. Thanks. Just to be sure, if you take a reasonably recent version of Haskell, the library "just works" for you? Because if that's the case I should debug on my side before I report back to you.

**Comment by andersk** [comment]
That’s what I’m telling you, yes. You are welcome to debug yourself or ask for help here—but to help you I’ll need to see more than zero information about what went wrong.

**Comment by andrejbauer** [comment]
Ok, thanks. (And apologies for reporting a problem the way my students do it to me.)
